version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   # Swagger開發時使用
    depends_on:
      - db
  
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.efcli
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

